// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/database-dump": {
    params: {};
  };
  "/antd-example": {
    params: {};
  };
  "/event-submissions": {
    params: {};
  };
  "/budget": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/org-members": {
    params: {};
  };
  "/event-form/:id?": {
    params: {
      "id"?: string;
    };
  };
  "/event-review/:id?": {
    params: {
      "id"?: string;
    };
  };
  "/event-overview": {
    params: {};
  };
  "/brainstorm": {
    params: {};
  };
  "/brainstorm/docs": {
    params: {};
  };
  "/brainstorm/sheets": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/database-dump" | "/antd-example" | "/event-submissions" | "/budget" | "/resources" | "/calendar" | "/org-members" | "/event-form/:id?" | "/event-review/:id?" | "/event-overview" | "/brainstorm" | "/brainstorm/docs" | "/brainstorm/sheets";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/login" | "/database-dump" | "/antd-example" | "/event-submissions" | "/budget" | "/resources" | "/calendar" | "/org-members" | "/event-form/:id?" | "/event-review/:id?" | "/event-overview" | "/brainstorm" | "/brainstorm/docs" | "/brainstorm/sheets";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/database-dump.tsx": {
    id: "routes/database-dump";
    page: "/database-dump";
  };
  "routes/antd-example.tsx": {
    id: "routes/antd-example";
    page: "/antd-example";
  };
  "routes/event-submissions.tsx": {
    id: "routes/event-submissions";
    page: "/event-submissions";
  };
  "routes/budget.tsx": {
    id: "routes/budget";
    page: "/budget";
  };
  "routes/resources.tsx": {
    id: "routes/resources";
    page: "/resources";
  };
  "routes/calendar.tsx": {
    id: "routes/calendar";
    page: "/calendar";
  };
  "routes/org-members.tsx": {
    id: "routes/org-members";
    page: "/org-members";
  };
  "routes/_event-layout.tsx": {
    id: "routes/_event-layout";
    page: "/" | "/event-form/:id?" | "/event-review/:id?";
  };
  "routes/event-form.tsx": {
    id: "routes/event-form";
    page: "/event-form/:id?";
  };
  "routes/event-review.tsx": {
    id: "routes/event-review";
    page: "/event-review/:id?";
  };
  "routes/event-overview.tsx": {
    id: "routes/event-overview";
    page: "/event-overview";
  };
  "routes/brainstorm.tsx": {
    id: "routes/brainstorm";
    page: "/brainstorm" | "/brainstorm/docs" | "/brainstorm/sheets";
  };
  "routes/brainstorm/docs.tsx": {
    id: "routes/brainstorm/docs";
    page: "/brainstorm/docs";
  };
  "routes/brainstorm/sheets.tsx": {
    id: "routes/brainstorm/sheets";
    page: "/brainstorm/sheets";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_layout": typeof import("./src/routes/_layout.tsx");
  "routes/index": typeof import("./src/routes/index.tsx");
  "routes/login": typeof import("./src/routes/login.tsx");
  "routes/database-dump": typeof import("./src/routes/database-dump.tsx");
  "routes/antd-example": typeof import("./src/routes/antd-example.tsx");
  "routes/event-submissions": typeof import("./src/routes/event-submissions.tsx");
  "routes/budget": typeof import("./src/routes/budget.tsx");
  "routes/resources": typeof import("./src/routes/resources.tsx");
  "routes/calendar": typeof import("./src/routes/calendar.tsx");
  "routes/org-members": typeof import("./src/routes/org-members.tsx");
  "routes/_event-layout": typeof import("./src/routes/_event-layout.tsx");
  "routes/event-form": typeof import("./src/routes/event-form.tsx");
  "routes/event-review": typeof import("./src/routes/event-review.tsx");
  "routes/event-overview": typeof import("./src/routes/event-overview.tsx");
  "routes/brainstorm": typeof import("./src/routes/brainstorm.tsx");
  "routes/brainstorm/docs": typeof import("./src/routes/brainstorm/docs.tsx");
  "routes/brainstorm/sheets": typeof import("./src/routes/brainstorm/sheets.tsx");
};